'use client';
import {useEffect,useState,useRef} from 'react';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {ArrowUpRight,CheckCircle2} from 'lucide-react';
import {topics,validateEnquiry,Enquiry} from '@/lib/enquiry';
const initial={name:'',organization:'',email:'',phone:'',topic:'',message:'',website:''};
export default function ContactForm(){const [values,setValues]=useState(initial);const [busy,setBusy]=useState(false);const lock=useRef(false);const [error,setError]=useState('');const [receipt,setReceipt]=useState('');
useEffect(()=>{const topic=new URLSearchParams(window.location.search).get('topic');if(topic&&topics.includes(topic))setValues(v=>({...v,topic}));},[]);
async function send(input:unknown){if(lock.current)throw new Error('A message is already being sent.');const data=validateEnquiry(input);setValues({...initial,...data});lock.current=true;setBusy(true);setError('');try{const response=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const result=await response.json() as {id:string;error?:string};if(!response.ok)throw new Error(result.error||'Your message could not be saved. Please try again.');setReceipt(result.id);return {status:'received',reference:result.id};}catch(e){const message=e instanceof Error?e.message:'Something went wrong. Please try again.';setError(message);throw new Error(message);}finally{lock.current=false;setBusy(false);}}
const sender=useRef(send);sender.current=send;
useEffect(()=>{type ToolContext={registerTool:(tool:Record<string,unknown>,options:{signal:AbortSignal})=>void|Promise<void>};const context=(document as Document&{modelContext?:ToolContext}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();try{void Promise.resolve(context.registerTool({name:'submit_techsavvy_enquiry',title:'Send an enquiry to Techsavvy Ideas',description:'Submit an enquiry with the user’s approval. Stores the message and shows a receipt in the contact form.',inputSchema:{type:'object',properties:{name:{type:'string',maxLength:120},organization:{type:'string',maxLength:160},email:{type:'string',maxLength:254},phone:{type:'string',maxLength:50},topic:{type:'string',enum:topics},message:{type:'string',maxLength:5000}},required:['name','email','topic','message'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:(input:unknown)=>sender.current(input)},{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort();},[]);
if(receipt)return <div className="form-success" role="status"><CheckCircle2 size={42} strokeWidth={1.3}/><h2>Message received.</h2><p>Thank you for starting a conversation. Your enquiry has been saved.</p><p className="receipt">Reference: {receipt}</p><button className="button secondary" onClick={()=>{setValues(initial);setReceipt('');}}>Send another message <ArrowUpRight size={18}/></button></div>;
return <form className="contact-form" onSubmit={async e=>{e.preventDefault();try{await send(values);}catch(err){setError(err instanceof Error?err.message:'Please check your message.');}}}><div className="form-grid">{([['name','Name','text',true,120,'name'],['organization','Organization','text',false,160,'organization'],['email','Email','email',true,254,'email'],['phone','Phone','tel',false,50,'tel']] as const).map(([key,label,type,required,maxLength,autoComplete])=><label key={key} htmlFor={key}>{label}{required&&' *'}<Input id={key} name={key} value={values[key]} type={type} required={required} maxLength={maxLength} autoComplete={autoComplete} disabled={busy} onChange={e=>setValues(v=>({...v,[key]:e.target.value}))}/></label>)}</div><div className="form-field"><label htmlFor="topic">What would you like to discuss? *</label><Select value={values.topic||null} onValueChange={v=>setValues(prev=>({...prev,topic:v||''}))} disabled={busy}><SelectTrigger id="topic" className="topic-select"><SelectValue placeholder="Select a topic"/></SelectTrigger><SelectContent>{topics.map(t=><SelectItem key={t} value={t}>{t}</SelectItem>)}</SelectContent></Select></div><label htmlFor="message">Message *<Textarea id="message" name="message" rows={6} value={values.message} onChange={e=>setValues(v=>({...v,message:e.target.value}))} required maxLength={5000} disabled={busy} placeholder="Tell us what you have in mind…"/></label><div className="honey" aria-hidden="true"><label>Website<Input tabIndex={-1} autoComplete="off" value={values.website} onChange={e=>setValues(v=>({...v,website:e.target.value}))}/></label></div><p className="form-note">Your details will be used to respond to your enquiry. Please avoid sharing confidential information at this stage.</p>{error&&<p className="form-error" role="alert">{error}</p>}<button type="submit" className="button" disabled={busy}>{busy?'Sending…':'Send Message'}<ArrowUpRight size={18}/></button><p className="form-note">* Required fields</p></form>}


