import Link from 'next/link';
import {ArrowUpRight, ArrowRight, Lightbulb, FlaskConical, Blocks, Radio, TrendingUp, BrainCircuit, Code2, Bot, Network, ChartNoAxesCombined, Cloud, ShieldCheck, Orbit} from 'lucide-react';
export const stages=[['Imagine','Identify problems, opportunities and possibilities.',Lightbulb],['Innovate','Research and develop new ideas and approaches.',FlaskConical],['Build','Turn concepts into products, platforms, systems and devices.',Blocks],['Deploy','Put technology to work in the real world.',Radio],['Scale','Commercialize, grow and create lasting value.',TrendingUp]] as const;
export const technologies=[['Artificial Intelligence','Intelligent systems that automate tasks, generate insights and enable better decisions.',BrainCircuit],['Software & Digital Platforms','Web, mobile, cloud and enterprise platforms that connect people, processes and opportunities.',Code2],['Automation & Robotics','Technology that enables machines and systems to perform tasks with greater speed, precision and intelligence.',Bot],['IoT & Smart Technology','Connected devices and sensors that collect information, communicate and respond intelligently.',Network],['Data & Analytics','Turning data into insights that support better decisions and performance.',ChartNoAxesCombined],['Cloud & Digital Infrastructure','Scalable technology infrastructure for modern digital operations.',Cloud],['Cybersecurity','Technologies and systems designed to protect information, platforms and digital operations.',ShieldCheck],['Emerging Technologies','Exploring new technologies and their potential to create entirely new products, services and business models.',Orbit]] as const;
export const ventures=[['Ideas','Early-stage concepts and opportunities.','Concepts and opportunities currently being explored.'],['In Development','Solutions currently being researched or built.','Technology solutions currently undergoing research, design or development.'],['Products','Completed technology solutions.','Completed technology solutions ready for deployment or market.'],['Ventures','Businesses and commercial opportunities developed from technology.','Businesses and commercial ventures created around technology and innovation.']];
export function ButtonLink({href,children,secondary=false}:{href:string;children:React.ReactNode;secondary?:boolean}){return <Link href={href} className={'button'+(secondary?' secondary':'')}>{children}<ArrowUpRight size={18}/></Link>}
export function Eyebrow({children}:{children:React.ReactNode}){return <div className="eyebrow"><span/>{children}</div>}
export function PageHero({label,title,text}:{label:string;title:string;text:string}){return <section className="page-hero wrap"><Eyebrow>{label}</Eyebrow><h1>{title}</h1><p className="intro">{text}</p></section>}
export function Lifecycle(){return <div className="stages">{stages.map(([t,d,Icon],i)=><article key={t}><div className="stage-top"><span className="number">0{i+1}</span><Icon size={26} strokeWidth={1.4}/></div><h3>{t}</h3><p>{d}</p>{i<4&&<ArrowRight className="stage-arrow" size={16}/>}</article>)}</div>}
export function TechnologyCards({details=false}:{details?:boolean}){return <div className={'tech-grid'+(details?' detailed':'')}>{technologies.map(([t,d,Icon],i)=>details?<article key={t} className="tech-card"><Icon size={30} strokeWidth={1.3}/><span className="number">0{i+1}</span><h3>{t}</h3><p>{d}</p></article>:<Link href={'/technology#area-'+i} key={t} className="tech-card"><Icon size={30} strokeWidth={1.3}/><ArrowUpRight className="card-arrow" size={17}/><h3>{t}</h3></Link>)}</div>}
export function CTA(){return <section className="cta wrap"><div><Eyebrow>Possibility starts with a conversation</Eyebrow><h2>Have a problem<br/>worth solving?</h2><p>Let's explore what technology can make possible.</p></div><ButtonLink href="/contact">Start a Conversation</ButtonLink></section>}
